name: reown_walletkit_wallet
description: An example wallet for Reown's WalletKit built with Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bs58: ^1.0.2
  convert: ^3.0.1
  cupertino_icons: ^1.0.2
  eth_sig_util: ^0.0.9
  fl_toast: ^3.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.2.0
  get_it_mixin: ^4.0.0
  http: ^1.2.2
  json_annotation: ^4.8.1
  kadena_dart_sdk: ^2.3.2
  package_info_plus: ^8.0.2
  pointycastle: ^3.9.1
  polkadart: ^0.4.6
  polkadart_keyring: ^0.4.3
  qr_bar_code_scanner_dialog:
    path: packages/qr-bar-code-scanner-dialog
  reown_walletkit:
    path: ../
  shared_preferences: ^2.2.2
  solana: ^0.30.4
  solana_web3: ^0.1.3

dev_dependencies:
  build_runner: ^2.4.7
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true
